### PR TITLE
Add const static lifetime test

### PR DESCRIPTION
**Pull request by killercup**
This is broken right no because of the stray space after the `&`

### CODE REVIEW

**Comment by killercup** [comment]
Fixed upstream in clippy but we need to wait for a new clippy release

**Comment by oli-obk** [comment]
No need to wait on clippy releases anymore, travis downloads clippy from github

bors r+

**Comment by oli-obk** [comment]
clippy's output has changed

**Comment by oli-obk** [comment]
> warning: Could not find remote branch staging.tmp to clone.

no idea what bors is up to...

**Comment by oli-obk** [comment]
I give up. @killercup any clues why bors doesn't work anymore?

One thing I've noticed is that it creates a `staging` branch, but travis looks at `staging.tmp` (it also builds `staging`, but the moment that one is done bors says it has been cancelled

@bors r+ one more try with reopening a PR, maybe there's just some weird leftover state?

**Comment by killercup** [comment]
There is no bors config in this repo. I'm surprised it ever worked. Let me add what the bors doc tell me to add.

**Comment by killercup** [comment]
Rebased against master which has bors adn travis config

**Comment by killercup** [comment]
And now:

bors r+

🤞

**Comment by killercup** [comment]
bors retry

**Pull request merged**
