### PR TITLE
Don't require clippy

### PR DESCRIPTION
**Pull request by Manishearth**
This makes it more suitable to use for epoch stuff

We also need better error reporting here :|

(Can this get a release?)

r? @killercup

### CODE REVIEW

**Comment by killercup** [comment]
Thanks! Not sure I like `-f`, other tools use this for `--force`. How about making it work like `rustfix diagnostics.json`?

Let's see if #49 fixed the CI error:

bors try

**Comment by nikomatsakis** [comment]
Or just no short form.

**Comment by killercup** [comment]
> error[E0463]: can't find crate for `rustc_const_eval`

Clippy fails to build with the current nightly?

**Pull request merged**
