### PR TITLE
Update to serde 1.0

### PR DESCRIPTION
**Pull request by oli-obk**
rustfix compiles on stable now...

### CODE REVIEW

**Comment by killercup** [comment]
Woah :O And it still works with rustc's JSON output?

**Comment by oli-obk** [comment]
trying that right now... the json output should be stable anyway...

**Comment by killercup** [comment]
Cool, let me know if it explodes :)

**Comment by oli-obk** [comment]
it does ^^ looking now what's going on

**Comment by oli-obk** [comment]
I think it's because cargo clippy returns an error exit code whenever it encounters something to report.

**Comment by oli-obk** [comment]
ah that was it. And already found a bug in clippy:

```
Info: use of `unwrap_or` followed by a function call
  --> tests/compiletest.rs:135:39-135:76
Suggestion - Replace:

    let end = text.find('\n').unwrap_or(text.len());

with:

    text.find('\n').unwrap_or_else(|| text.len())
```

**Pull request merged**
