### PR TITLE
Pretty print json

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by killercup** [comment]
Oh? This works with multiple json docs per file now?

**Comment by oli-obk** [comment]
Note the `into_iter` on the `Deserializer`. This has been a feature since idk how long :D but a very well hidden one.

Oh, yea comparing as Value makes much more sense... Or even compare as `Diagnostic`?

**Comment by killercup** [comment]
> Note the into_iter on the Deserializer. This has been a feature since idk how long :D but a very well hidden one.

TIL!

> Or even compare as Diagnostic?

Sure! This way we are a bit more resilient to changes in the format we don't care about

**Comment by killercup** [comment]
Thanks!

bors r+

**Comment by oli-obk** [comment]
ugh yea, you need to take away the "Merge pull request" button, otherwise I'll keep forgetting. I think you can set it to only turn green if bors is green

**Comment by killercup** [comment]
Ha, good point, I totally forgot about bors with my last pr as well. Also a good chance to play with github settings!

Merging into master now requires a PR with review and green bors. Let me know if it's not useful, though.

**Pull request merged**
