### PR TITLE
Allow choosing a specific replacement if multiple apply

### LINKED ISSUE #30: Don't treat a suggestion with multiple possibilities as multiple suggestions
Right now, if we get a suggestion that has two alternatives, rustfix shows them as single suggestions after each other. Instead it should show that this suggestion has alternatives and require one to enter a number to choose the replacement to use.

### PR DESCRIPTION
**Pull request by oli-obk**
Initial work. Will need to improve the output...

fixes #30

### CODE REVIEW

**Comment by killercup** [comment]
Woah, thanks! Testing this as we speak! First comment: Can you make it accept <kbd>r</kbd> as the first suggestion so I can just continue hammer <kbd>r</kbd><kbd>r</kbd><kbd>r</kbd><kbd>r</kbd> until I see something horribly wrong? ;)

- - -

Man, I really want to work on this tool, but I have so little time :( E.g., we should be able to use the byte positions of spans (they are now relative to their files if I remember a rust PR correctly), and also batch edit files instead of that stupid read-replace-save dance for each suggestion. And we can probably make the testing story a bit easier by supporting single files in addition to crates, so the roundtrip time for human testing is shorter.

**Comment by oli-obk** [comment]
> Can you make it accept r as the first suggestion so I can just continue hammer rrrr until I see something horribly wrong? ;)

How about having it accept it only if there's only a single suggestion?

**Comment by oli-obk** [comment]
>  How about having it accept it only if there's only a single suggestion?

Well that's what I did now ;)

**Pull request merged**
