### PR TITLE
fix clippy command redirection

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by killercup** [comment]
Hah, thanks! I'm using fish locally, so my bash skills are not up to par these days.

**Comment by Manishearth** [comment]
I think actually it can be just `2>` without the &, not sure. works for me.

**Comment by Manishearth** [comment]
Oh, `&` is "both"

**Comment by killercup** [comment]
Nice. That's good to know, 'cause that what fish uses as well.

**Pull request merged**
